In [2]:
import numpy as np
import re
# Define the path to your .npy file
files_path = ['T_est_FashionMNIST0.3.npy', 'T_est_FashionMNIST0.6.npy', 'T_est_CIFAR.npy'] 
out = [re.search(r'^T_est_(.+?)\.npy$', f).group(1) for f in files_path]
# Load the data from the .npy file
i = 0
while i < len(files_path):
    print(out[i])
    data = np.load(files_path[i])
    print(data)
    i += 1



FashionMNIST0.3
[[0.59931195 0.21518724 0.18550085]
 [0.13033418 0.5860704  0.28359544]
 [0.23658225 0.19241878 0.5709989 ]]
FashionMNIST0.6
[[0.4564011  0.24938016 0.29421872]
 [0.31682408 0.35877925 0.32439667]
 [0.29789683 0.2788986  0.42320457]]
CIFAR
[[0.34947687 0.32665217 0.32387096]
 [0.32095367 0.3588615  0.32018486]
 [0.33052602 0.32406148 0.34541246]]
